### ISSUE TITLE
Broken link in SECURITY.md

### ISSUE THREAD

**Issue by mutexdeveloper** [japandotorg/LemonCord#13]
**Summary**
The link to fill out a security issue is broken. 
https://github.com/japandotorg/LemonCord/blob/6e73dc05d375ec0f5c0c4bb21002552510729d75/SECURITY.md?plain=1#L22
The [link](https://github.com/japandotorg/LemonCord/security/advisories/new) returns 404.

**Steps To Reproduce**
[Click here as somebody without write access](https://github.com/japandotorg/LemonCord/security/advisories/new)

**Expected Behavior**
A form allowing somebody to fill a security report.

**Platform And Versions**
**Not applicable**

OS: Arch Linux (6.1.8-arch1-1)
Rustc: 
```
cargo 1.68.0-nightly (2381cbdb4 2022-12-23)
release: 1.68.0-nightly
commit-hash: 2381cbdb4e9b07090f552d34a44a529b6e620e44
commit-date: 2022-12-23
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.15.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Arch Linux Rolling Release [64-bit]
```
- LemonCord: 0.11

**Additional Context**
- If there's anything else to say, please do so here.

**Comment by japandotorg** [comment]
![image](http://cdn.melonbot.io/335.png)

The link seem to be working fine for me, however we gotta verify if it's working for everyone else, or is it just me.

**Comment by mutexdeveloper** [comment]
> _snip_
> 
> The link seem to be working fine for me, however we gotta verify if it's working for everyone else, or is it just me.

Likely due to you having write on the repository

**Comment by japandotorg** [comment]
Can't repo, everyone I asked said that the link works for them.

**Comment by mutexdeveloper** [comment]
Very strange.
It started working for me.
