### ISSUE TITLE
Prebuild/AppImage, or something similar

### ISSUE THREAD

**Issue by ghost** [japandotorg/LemonCord#18]
**Describe The Feature Request**
Make an AppImage (or something similar), so that building is not required

**Expected Behaviour**
Issue with building, error:
thread 'main' panicked at 'Failed to open icon path.: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/main.rs:283:14

this error was produced, after following the instructions on readme.

**Anything Else?**
- Would really like to try it, tbh
- visited melon.io discord server, there is no help channel for LemonCord

**Comment by japandotorg** [comment]
Can I know your OS?
Yes there's no support channel but you can ping @inthedark.org (LEMON) in the support server for in-app support for LemonCord.

**Comment by ghost** [comment]
Arch Linux
Linux Version: 6.4.1

It's not actually clear how to use the discord channel properly; it says I have no access to any of the text channels.

**Comment by japandotorg** [comment]
You just need to join, bots will assign roles to you as soon as possible, make sure to use the keyword "lemon" to ping me, if you mention me you'll get timed out so.

**Comment by streetsamurai00mi** [comment]
> Arch Linux
> Linux Version: 6.4.1

You can use my [aur package](https://aur.archlinux.org/packages/lemon-cord-git)
