### ISSUE TITLE
Compatability issue in main.

### ISSUE THREAD

**Issue by ghost** [japandotorg/LemonCord#3]
https://github.com/japandotorg/LemonCord/blob/c590a6462d1a286d16cf731abcedde97ebfaed0a/src/main.rs#L9
According to [WRY documentation](https://docs.rs/wry/0.23.4/wry/application/platform/index.html), This module is only in place for  the specific operating system. 
This removes compatibility with other operating systems.

**Comment by japandotorg** [comment]
Wry uses the [tao](https://github.com/tauri-apps/tao) crate internally for it's window functionality and unfortunately to set the [taskbar icon](https://github.com/tauri-apps/tao/blob/5d8bf51d7ea2ea89feb4e8b003e583fed69bf300/src/platform/windows.rs#L208) we need the `WindowBuilderExtWindows` trait unless I'm unaware of some other way to achieve the goal? Also I'm looking forward on making the client `cross-platform`, so ig I'll have to eventually come up with something to set the taskbar icon without the need of using the `WindowBuilderExtWindows` trait, maybe read more wry documentation?

PRs are always welcome tho.

**Comment by japandotorg** [comment]
> Is this required on windows?

No, it's not required in anyway, the only thing it does is to add a little aesthetic to the app (in windows), which is the taskbar icon.
![image](https://user-images.githubusercontent.com/78662983/213755352-c338cd40-fa3e-4a30-8adc-d9773b4a4877.png)

> Shouldn't this be enough?
After looking at it properly once, yes, that indeed is enough which means the windows extension trait and the `with_taskbar_icon` is safe to be removed.
